### ISSUE TITLE
Understanding use case

### ISSUE THREAD

**Issue by joeybaer** [innovationnorway/terraform-http-github-ip-ranges#2]
First off cool use of TF 0.12 functionality here!

In response to your note , just wanted to share this example and see if there was something you were thinking of that I missed as this module and the example below would both be subject to rate limiting by IP address https://developer.github.com/v3/#rate-limiting

```
provider "github" {
  anonymous  = true
  individual = true
}

data "github_ip_ranges" "default" {}

output "hooks" {
  value = "${data.github_ip_ranges.default.hooks}"
}
```

Again while I decided not to use it, probably works for you , just wanted to ensure you knew of the above example as the note seemed to contradict my experience.

**Comment by joakimhellum-in** [comment]
Hi, @joeybaer 

The purpose of this modue is to avoid generating GitHub tokens just to be able to get the GitHub IP-ranges for some workflows, as described here:

> Note: The github provider needs to be configured with the proper credentials before it can be used. The http provider requires no configuration. If you are already using the GitHub provider, then you can use the github_ip_ranges data source.

However is now fixed in the provider with reference to this pull request:
https://github.com/terraform-providers/terraform-provider-github/pull/255

And such there is no reason to use this module anymore.

I agree GitHub's weird window-based rate limiting don't work well with Terraform, which not only applies this Terraform module, or even to the GitHub provider. However this is not a problem for us. We run Terraform in a workflow where the originating IP address changes. Rate limiting has been discussed multiple times in the repo of the provider, for example https://github.com/hashicorp/terraform/issues/6016
